# First stage: build the application as a single war file
FROM maven:3.2-jdk-8 AS builder
COPY /app/src /usr/src/app/src
COPY /app/pom-secure.xml /usr/src/app/pom.xml
RUN mvn -f /usr/src/app/pom.xml clean package

# Second stage: copy only the jar to the minimal java runtime 
FROM amazoncorretto:8u392-al2023-jre
ARG APPLICATION_USER=appuser
RUN adduser --no-create-home -u 1001 ${APPLICATION_USER} && mkdir /app && chown -R $APPLICATION_USER /app
USER 1001

COPY --from=builder --chown=1001:1001 /usr/src/app/target/cisdemo.war /app/cisdemo.war
WORKDIR /app


CMD ["java", "-jar", "/app/cisdemo.war"]