version: '3.3'
services:
  mariadb:
    image: mariadb:10.6.2
    container_name: mariadb
    user: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: 'user'
      MYSQL_DATABASE: 'blab'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # mounting the data
    volumes:
      - type: volume
        source: db
        target: /docker-entrypoint-initdb.d
        read_only: true

  java_application:
    image: cisapplication
    depends_on: 
      - mariadb
    container_name: app
    restart: always
    environment:
      RDS_HOSTNAME: 'mariadb'

    ports:
      - '8080:8080'
    expose:
      - '8080'
    volumes:
      - type: volume
        source: db_creds
        target: /usr/db_creds
        read_only: true
    security_opt:
      - no-new-privileges:true
volumes:
    db:
        external: true
    db_creds:
        external: true