# First stage: build the application as a single war file
FROM maven:3.2-jdk-8 AS builder
COPY /app/src /usr/src/app/src
COPY /app/pom-secure.xml /usr/src/app/pom.xml
RUN mvn -f /usr/src/app/pom.xml clean package

# Second stage: copy only the jar to the minimal java runtime 
FROM amazoncorretto:8u392-al2023-jre
COPY --from=builder /usr/src/app/target/cisdemo.war cisdemo.war
USER 1001
CMD ["java", "-jar", "cisdemo.war"]