version: '3.3'
services:
  mariadb:
    image: mariadb:10.6.2
    container_name: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_DATABASE: 'blab'

    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - type: volume
        source: db
        target: /docker-entrypoint-initdb.d
        read_only: true

  java_application:
    image: verademo
    depends_on: 
      - mariadb
    container_name: app
    restart: always
    environment:
      RDS_HOSTNAME: 'mariadb'
      RDS_PASSWORD: 'z2^E6J4$;u;d'

    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '8080:8080'
    expose:
      - '8080'
    volumes:
      - type: volume
        source: db
        target: /docker-entrypoint-initdb.d
        read_only: true
volumes:
    db:
        external: true